import { userType } from "./users";

export const userList: userType[] = [
  {
    uid: "1",
    firstName: "Aditya",
    lastName: "Singh",
    username: "Adi1210",
    password: "@ditya1210",
    role: ["admin"],
    isLocked: false,
  },
  {
    uid: "2",
    firstName: "Neha",
    lastName: "Sharma",
    username: "Neha2024",
    password: "Neha@2024",
    role: ["student"],
    isLocked: false,
  },
  {
    uid: "3",
    firstName: "Rohan",
    lastName: "Kumar",
    username: "Rohan99",
    password: "Rohan#99",
    role: ["attendant"],
    isLocked: true,
  },
  {
    uid: "4",
    firstName: "Priya",
    lastName: "Patel",
    username: "Priya_19",
    password: "Priya*19",
    role: ["warden"],
    isLocked: false,
  },
  {
    uid: "5",
    firstName: "Suman",
    lastName: "Verma",
    username: "SumanV",
    password: "Suman@verma",
    role: ["guard"],
    isLocked: false,
  },
  {
    uid: "6",
    firstName: "Amit",
    lastName: "Desai",
    username: "Amit123",
    password: "Amit@123",
    role: ["student"],
    isLocked: true,
  },
  {
    uid: "7",
    firstName: "Sara",
    lastName: "Khan",
    username: "Sara789",
    password: "Sara!789",
    role: ["student"],
    isLocked: false,
  },
  {
    uid: "8",
    firstName: "Vikram",
    lastName: "Singh",
    username: "Vikram2021",
    password: "Vikr@m2021",
    role: ["admin"],
    isLocked: false,
  },
  {
    uid: "9",
    firstName: "Meera",
    lastName: "Kapoor",
    username: "Meera_K",
    password: "Meera@999",
    role: ["attendant"],
    isLocked: false,
  },
  {
    uid: "10",
    firstName: "Rajesh",
    lastName: "Shah",
    username: "RajShah",
    password: "Raj#Shah",
    role: ["warden"],
    isLocked: true,
  },
  {
    uid: "11",
    firstName: "Tina",
    lastName: "Joseph",
    username: "TinaJ",
    password: "Tina@Jo",
    role: ["guard"],
    isLocked: false,
  },
  {
    uid: "12",
    firstName: "Anil",
    lastName: "Kumar",
    username: "AnilK",
    password: "Anil#888",
    role: ["admin"],
    isLocked: false,
  },
  {
    uid: "13",
    firstName: "Pooja",
    lastName: "Nair",
    username: "PoojaNair",
    password: "Pooja*123",
    role: ["student"],
    isLocked: false,
  },
  {
    uid: "14",
    firstName: "Sunil",
    lastName: "Mehta",
    username: "SunilM",
    password: "Sunil@mehta",
    role: ["attendant"],
    isLocked: true,
  },
  {
    uid: "15",
    firstName: "Kiran",
    lastName: "Das",
    username: "KiranD",
    password: "Kiran#D",
    role: ["warden"],
    isLocked: false,
  },
  {
    uid: "16",
    firstName: "Nikita",
    lastName: "Roy",
    username: "NikitaR",
    password: "Niki!23",
    role: ["guard"],
    isLocked: false,
  },
  {
    uid: "17",
    firstName: "Ajay",
    lastName: "Bansal",
    username: "AjayB",
    password: "Ajay@bansal",
    role: ["student"],
    isLocked: false,
  },
  {
    uid: "18",
    firstName: "Anjali",
    lastName: "Jain",
    username: "AnjaliJ",
    password: "Anjali#888",
    role: ["attendant"],
    isLocked: true,
  },
  {
    uid: "19",
    firstName: "Rahul",
    lastName: "Yadav",
    username: "RahulY",
    password: "Rahul@123",
    role: ["warden"],
    isLocked: false,
  },
  {
    uid: "20",
    firstName: "Sonia",
    lastName: "Ghosh",
    username: "SoniaG",
    password: "Sonia*Ghosh",
    role: ["guard"],
    isLocked: true,
  },
];
